kind: pipeline
type: docker
name: buildah

steps:
  - name: build
    image: alpine:latest
    commands:
      - apk update && apk add buildah
      - export MYTAG="mytag"
      - export container=$(buildah from docker.io/alpine:latest)
      - buildah run "$container" -- apk update
      - buildah run "$container" -- apk add git
      - buildah run "$container" -- apk add go
      - buildah commit --format docker "$container" "$MYTAG"
      - buildah push "$MYTAG"
