kind: pipeline
type: docker
name: buildah

steps:
  - name: build
    image: alpine:3.13
    commands:
      - sed -i 's/v3\.13/edge/g' /etc/apk/repositories
      - echo "http://dl-3.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
      - apk upgrade --update-cache --available
      - apk add buildah
      - export MYTAG="mytag"
      - export container=$(buildah from docker.io/alpine:latest)
      - buildah run "$container" -- apk update
      - buildah run "$container" -- apk add git
      - buildah run "$container" -- apk add go
      - buildah commit --format docker "$container" "$MYTAG"
      - buildah push "$MYTAG"
