kind: pipeline
type: docker
name: buildah

steps:
  - name: build
    image: docker.io/python:3.6-slim
    privileged: true
    commands:
      - export MYTAG="mytag"
      - export container="somecontainer"
      - apt-get update
      - echo "after update"
      - apt-get install -y build-essential git
      - echo "after install"
